
package org.apache.fineract.infrastructure.configuration.domain;
import java.time.LocalDate;
import org.apache.fineract.infrastructure.cache.domain.CacheType;
public interface ConfigurationDomainService {
    boolean isMakerCheckerEnabledForTask(String taskPermissionCode);
    boolean isAmazonS3Enabled();
    boolean isRescheduleFutureRepaymentsEnabled();
    boolean isRescheduleRepaymentsOnHolidaysEnabled();
    boolean allowTransactionsOnHolidayEnabled();
    boolean allowTransactionsOnNonWorkingDayEnabled();
    boolean isConstraintApproachEnabledForDatatables();
    boolean isEhcacheEnabled();
    void updateCache(CacheType cacheType);
    Long retrievePenaltyWaitPeriod();
    boolean isPasswordForcedResetEnable();
    Long retrievePasswordLiveTime();
    Long retrieveGraceOnPenaltyPostingPeriod();
    Long retrieveOpeningBalancesContraAccount();
    boolean isSavingsInterestPostingAtCurrentPeriodEnd();
    Integer retrieveFinancialYearBeginningMonth();
    Integer retrieveMinAllowedClientsInGroup();
    Integer retrieveMaxAllowedClientsInGroup();
    boolean isMeetingMandatoryForJLGLoans();
    int getRoundingMode();
    boolean isBackdatePenaltiesEnabled();
    boolean isOrganisationstartDateEnabled();
    LocalDate retrieveOrganisationStartDate();
    boolean isPaymnetypeApplicableforDisbursementCharge();
    boolean isInterestChargedFromDateSameAsDisbursementDate();
    boolean isSkippingMeetingOnFirstDayOfMonthEnabled();
    boolean isInterestToBeRecoveredFirstWhenGreaterThanEMI();
    boolean isPrincipalCompoundingDisabledForOverdueLoans();
    Long retreivePeroidInNumberOfDaysForSkipMeetingDate();
    boolean isChangeEmiIfRepaymentDateSameAsDisbursementDateEnabled();
    boolean isDailyTPTLimitEnabled();
    Long getDailyTPTLimit();
    void removeGlobalConfigurationPropertyDataFromCache(String propertyName);
    boolean isSMSOTPDeliveryEnabled();
    boolean isEmailOTPDeliveryEnabled();
    Integer retrieveOTPCharacterLength();
    Integer retrieveOTPLiveTime();
    boolean isSubRatesEnabled();
    boolean isFirstRepaymentDateAfterRescheduleAllowedOnHoliday();
    String getAccountMappingForPaymentType();
    String getAccountMappingForCharge();
    boolean isNextDayFixedDepositInterestTransferEnabledForPeriodEnd();
    boolean retrievePivotDateConfig();
    boolean isRelaxingDaysConfigForPivotDateEnabled();
    Long retrieveRelaxingDaysConfigForPivotDate();
    boolean isBusinessDateEnabled();
    boolean isCOBDateAdjustmentEnabled();
    boolean isReversalTransactionAllowed();
}
