
package org.apache.fineract.portfolio.loanaccount.domain;
public enum LoanEvent {
    LOAN_CREATED, 
    LOAN_REJECTED, 
    LOAN_WITHDRAWN, 
    LOAN_APPROVED, 
    LOAN_APPROVAL_UNDO, 
    LOAN_RECOVERY_PAYMENT, 
    LOAN_DISBURSED, 
    LOAN_DISBURSAL_UNDO, 
    LOAN_DISBURSAL_UNDO_LAST, 
    LOAN_REPAYMENT_OR_WAIVER, 
    REPAID_IN_FULL, 
    WRITE_OFF_OUTSTANDING, 
    WRITE_OFF_OUTSTANDING_UNDO, 
    LOAN_RESCHEDULE, 
    INTERST_REBATE_OWED, 
    LOAN_OVERPAYMENT, 
    LOAN_CHARGE_PAYMENT, 
    LOAN_CLOSED, 
    LOAN_EDIT_MULTI_DISBURSE_DATE, 
    LOAN_REFUND, 
    LOAN_FORECLOSURE, 
    LOAN_CREDIT_BALANCE_REFUND;
}
